FROM docker.io/library/rust:trixie AS rust
# Rust in debian stable is too old to build gitoxide/git-lint

ARG registry=localhost
ARG tag=latest

FROM ghcr.io/jan-matejka/debian:latest

COPY --from=rust /usr/local/cargo /usr/local/cargo
COPY --from=rust /usr/local/rustup /usr/local/rustup

ENV PATH=/usr/local/cargo/bin:$PATH \
    RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo

RUN chmod a+w $RUSTUP_HOME $CARGO_HOME

RUN <<EOF
apt-get update
pkgs="
  build-essential
  ca-certificates
  curl
  debhelper-compat
  devscripts
  docker-compose
  dram
  g++
  gdb
  git
  git-buildpackage
  gnupg
  gpg
  jq
  libargparse-dev
  libfmt-dev
  make
  podman
  python3-docutils
  strace
  xdgenv
  zsh
"
apt-get install -y ${pkgs}
EOF

RUN rustup component add rustfmt

USER user
RUN mkdir /home/user/.gnupg && chmod 700 /home/user/.gnupg

WORKDIR /home/user/src
