[package]
name = "jm-util"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = 'jm-lcpp'
path = 'core/jm-lcpp.rs'
